   apiVersion: serving.knative.dev/v1alpha1
   kind: Service
   metadata:
     name: app-from-source
     namespace: default
   spec:
     runLatest:
       configuration:
         build:
           apiVersion: build.knative.dev/v1alpha1
           kind: Build
           spec:
             serviceAccountName: build-bot
             source:
               git:
                 url: https://github.com/navarasu/goknative.git
                 revision: master
             template:
               name: kaniko
               arguments:
                 - name: IMAGE
                   value: docker.io/navarasu/app-from-source:latest
             timeout: 10m
         revisionTemplate:
           spec:
             container:
               image: docker.io/navarasu/app-from-source:latest
               imagePullPolicy: Always
